### ISSUE TITLE
Just a quick one - firefox error on sqlite post

### ISSUE THREAD

**Issue by Rotario** [phiresky/blog#7]
Hi, just got a SharedArrayBuffer error on firefox while trying to run one of your code blocks on the sqlite post:
https://stackoverflow.com/questions/64650119/react-error-sharedarraybuffer-is-not-defined-in-firefox
Hope this helps!

**Comment by phiresky** [comment]
Thanks for the info. Yeah I know about the issue, I'm a firefox user myself - that's why I added a link to netlify where it should work. It's unfortunate, but nothing I myself can do about it since problem is that you can't set those headers on github pages. There's an open issue about that somewhere but i'm not sure if GH will ever fix it.
